const dims=[['length','Länge'],['width','Breite'],['height','Höhe']];
const standards=[12,16,18,20,24,28,32,35,43,48,50,64,72,87,100,144,200,350];
let category='Fahrzeug',lastScaleText='',lastOriginalText='';
const $=id=>document.getElementById(id);
const t=value=>window.BloxxI18n?.t(value)||value;
const locale=()=>window.BloxxI18n?.locale||'de-DE';
const format=(n,d=1)=>new Intl.NumberFormat(locale(),{maximumFractionDigits:d}).format(n);
function build(target,prefix,units,selected){$(target).innerHTML=dims.map(([key,label])=>`<div class="dimension"><label for="${prefix}-${key}">${t(label)}</label><div class="dimension-row"><input id="${prefix}-${key}" type="number" min="0" step="any" inputmode="decimal" placeholder="optional"><select id="${prefix}-${key}-unit" aria-label="${t('Einheit')} ${t(label)}">${units.map(u=>`<option ${u===selected?'selected':''}>${u}</option>`).join('')}</select></div></div>`).join('')}
function rebuildInputs(){
 const values={};document.querySelectorAll('.dimension input,.dimension select').forEach(el=>values[el.id]=el.value);
 build('model-inputs','model',['mm','cm'],'cm');build('real-inputs','real',['mm','cm','m'],'m');build('reverse-inputs','reverse',['mm','cm'],'cm');
 Object.entries(values).forEach(([id,value])=>{const el=$(id);if(el)el.value=value});
}
rebuildInputs();
function toMM(value,unit){const n=parseFloat(String(value).replace(',','.'));if(!Number.isFinite(n)||n<=0)return null;return unit==='m'?n*1000:unit==='cm'?n*10:n}
function nearest(value){return standards.reduce((a,b)=>Math.abs(b-value)<Math.abs(a-value)?b:a)}
function notify(text){let el=document.querySelector('.app-toast');if(!el){el=document.createElement('div');el.className='app-toast';Object.assign(el.style,{position:'fixed',left:'50%',bottom:'20px',transform:'translateX(-50%)',background:'#111827',color:'#fff',padding:'11px 15px',borderRadius:'10px',zIndex:'100'});document.body.appendChild(el)}el.textContent=t(text);clearTimeout(el.timer);el.timer=setTimeout(()=>el.remove(),1800)}
async function copy(text){try{await navigator.clipboard.writeText(text);notify('Ergebnis kopiert')}catch{notify('Kopieren nicht möglich')}}
document.querySelectorAll('[data-category]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-category]').forEach(x=>x.classList.remove('active'));button.classList.add('active');category=button.dataset.category}));
document.querySelectorAll('[data-mode]').forEach(button=>button.addEventListener('click',()=>{const mode=button.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>{const active=x===button;x.classList.toggle('active',active);x.setAttribute('aria-selected',String(active))});$('scale-panel').hidden=mode!=='scale';$('original-panel').hidden=mode!=='original'}));
function calculateScale(){const results=[];dims.forEach(([key,label])=>{const model=toMM($(`model-${key}`).value,$(`model-${key}-unit`).value);const real=toMM($(`real-${key}`).value,$(`real-${key}-unit`).value);if(model&&real)results.push({label,scale:real/model})});if(!results.length){notify('Bitte mindestens ein passendes Maßpaar eingeben');return}const avg=results.reduce((s,x)=>s+x.scale,0)/results.length;const min=Math.min(...results.map(x=>x.scale)),max=Math.max(...results.map(x=>x.scale));const deviation=results.length>1?(max-min)/avg*100:0;let quality;if(results.length===1)quality='Nur ein Maß verwendet';else if(deviation<=5)quality='Sehr einheitlich skaliert';else if(deviation<=12)quality='Leichte proportionale Abweichungen';else quality='Deutlich unterschiedliche Maßstäbe';$('scale-empty').hidden=true;$('scale-output').hidden=false;$('average-scale').textContent=`1:${format(avg,1)}`;$('quality').textContent=t(quality);$('dimension-results').innerHTML=results.map(x=>`<div class="dimension-result"><span>${t(x.label)}</span><strong>1:${format(x.scale,1)}</strong></div>`).join('');const close=nearest(avg);const list=standards.filter(s=>Math.abs(s-close)<=Math.max(8,close*.35)).slice(0,7);$('standard-list').innerHTML=list.map(s=>`<span class="standard-item ${s===close?'nearest':''}">1:${s}</span>`).join('');const percent=100/avg;$('model-percent').textContent=`${format(percent,2)} %`;$('model-bar').style.width=`${Math.max(1,Math.min(100,percent))}%`;lastScaleText=`BloxxStar ${t('Maßstabsrechner')}\n${t('Objekt')}: ${t(category)}\n${results.map(x=>`${t(x.label)}: 1:${format(x.scale,1)}`).join('\n')}\n${t('Durchschnitt')}: 1:${format(avg,1)}\n${t('Nächster Standardmaßstab')}: 1:${close}\n${t('Bewertung')}: ${t(quality)}`}
$('calculate-scale').addEventListener('click',calculateScale);
$('reset-scale').addEventListener('click',()=>{document.querySelectorAll('#scale-panel input').forEach(x=>x.value='');$('scale-empty').hidden=false;$('scale-output').hidden=true});$('copy-scale').addEventListener('click',()=>copy(lastScaleText));
function calculateOriginal(){const scale=parseFloat($('known-scale').value);if(!Number.isFinite(scale)||scale<=0){notify('Bitte einen gültigen Maßstab eingeben');return}const results=[];dims.forEach(([key,label])=>{const model=toMM($(`reverse-${key}`).value,$(`reverse-${key}-unit`).value);if(model)results.push({label,mm:model*scale})});if(!results.length){notify('Bitte mindestens ein Modellmaß eingeben');return}$('original-empty').hidden=true;$('original-output').hidden=false;$('reverse-scale').textContent=`1:${format(scale,1)}`;$('original-results').innerHTML=results.map(x=>`<div class="dimension-result"><span>${t(x.label)}</span><strong>${x.mm>=1000?format(x.mm/1000,3)+' m':format(x.mm/10,1)+' cm'}</strong></div>`).join('');lastOriginalText=`BloxxStar ${t('Maßstabsrechner')}\n${t('Objekt')}: ${t(category)}\n${t('Maßstab')}: 1:${format(scale,1)}\n${results.map(x=>`${t(x.label)}: ${x.mm>=1000?format(x.mm/1000,3)+' m':format(x.mm/10,1)+' cm'}`).join('\n')}`}
$('calculate-original').addEventListener('click',calculateOriginal);
$('reset-original').addEventListener('click',()=>{document.querySelectorAll('#original-panel input').forEach(x=>x.value='');$('original-empty').hidden=false;$('original-output').hidden=true});$('copy-original').addEventListener('click',()=>copy(lastOriginalText));
function refreshLanguage(){rebuildInputs();if(!$('scale-output').hidden)calculateScale();if(!$('original-output').hidden)calculateOriginal()}
window.addEventListener('bloxxstar:languagechange',refreshLanguage);window.addEventListener('bloxxstar:i18nready',refreshLanguage);
let deferredPrompt;const installBtn=$('installBtn');window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();deferredPrompt=event;installBtn.style.display='block'});installBtn.addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;installBtn.style.display='none'});if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));